server:
  port: ${AUTH_SERVICE_PORT:0}

spring:
  application:
    name: AUTH-SERVICE
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
  sleuth:
    sampler:
      probability: 1

jwt:
  secret: ${JWT_SECRET_KEY}
