FROM adoptopenjdk/openjdk11:alpine
RUN apk update
RUN apk add bash curl
RUN mkdir /service
WORKDIR /service
COPY target/post-service-0.0.1.jar post-service.jar
COPY init.sh init.sh
RUN chmod +x init.sh
ENTRYPOINT ["./init.sh", "post-service", "true", "discovery-service:8761", "config-service:9296", "gateway-service:9191"]
