server:
  port: 9191

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTH-SERVICE
                fallbackuri: forward:/v1/fallbacks/auth
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/v1/fallbacks/users
            - name: AuthenticationFilter
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/v1/posts/**
          filters:
            - name: CircuitBreaker
              args:
                name: POST-SERVICE
                fallbackuri: forward:/v1/fallbacks/posts
            - name: AuthenticationFilter

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

open:
  routes: /v1/auth/login
