server:
  port: ${USER_SERVICE_PORT:0}

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://${ZIPKIN_URL:localhost}:9411
  sleuth:
    sampler:
      probability: 1

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:2000}
        readTimeout: ${FEIGN_READ_TIMEOUT:2000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}
