server:
  port: ${CONFIG_SERVICE_PORT:9296}

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          default-label: main
          clone-on-start: true
          uri: ${CONFIG_REPO_URL}

eureka:
  instance:
    hostname: ${DISCOVERY_SERVICE_URL:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_URL:localhost}:8761/eureka
