server:
  port: ${CONFIG_SERVICE_PORT:9296}

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: ${CONFIG_REPO_URL:file:///D:/github-repos/config-server}
